[book]
authors = ["twocucao"]
language = "zh_CN"
multilingual = false
src = "src"
title = "HylaruCoder🇨🇳's knowledge-repo"

[output.html]
default-theme = "rust"
no-section-label = true
additional-css = ["custom.css"]

[output.html.fold]
enable = true
level = 1


